version: "3.8"

services:
  booking-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booking-service
    ports:
      - "9090:9090"
    networks:
      - hotelio-net
    environment:
      DB_HOST: booking-service-db
      DB_PORT: 5432
      DB_USER: booking
      DB_PASSWORD: booking
      DB_NAME: booking_service
      USER_SERVICE_URL: http://hotelio-monolith:8080/api/users
      HOTEL_SERVICE_URL: http://hotelio-monolith:8080/api/hotels
      REVIEW_SERVICE_URL: http://hotelio-monolith:8080/api/reviews
      PROMO_SERVICE_URL: http://hotelio-monolith:8080/api/promos
      APP_PORT: 9090
    depends_on:
      - booking-service-db

  booking-service-db:
    image: postgres:15
    container_name: booking-service-db
    environment:
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
      POSTGRES_DB: booking_service
    ports:
      - "5433:5432"
    volumes:
      - booking-service-db-data:/var/lib/postgresql/data
    networks:
      - hotelio-net

volumes:
  booking-service-db-data:

networks:
  hotelio-net:
    external: true
